---
name: Schema Validator

permissions:
  contents: read
  security-events: write

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Install CPAN dependencies
        run: |
          # cpanm --installdeps .
          cpanm -iqn --skip-satisfied Mojo::DOM JSON::MaybeXS Encode Getopt::Long Test::Most FindBin LWP::Protocol::https IPC::System::Simple Locale::Country DateTime::Format::ISO8601 File::HomeDir

      - name: Run Schema.org validator
        run: |
          perl bin/validate-schema --file samples/sample.html --github

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: schema_validation.sarif
